import './style.css'
import './table.css'
import './404.css'
import './about.css'
import './index.css'
import './menu.css'
import './addTask.js'
import './menu.js'
import logo from './logo.png'
import image404 from './404.png'
import index from './index.png'